// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Button(Props) {
  var onClick = Props.onClick;
  var match = Props.className;
  var className = match !== undefined ? match : "";
  var children = Props.children;
  return React.createElement("button", {
              className: className,
              type: "button",
              onClick: onClick
            }, children);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
