// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var default_query = "ReasonReact";

var path_base = "https://hn.algolia.com/api/v1";

var path_search = "/search";

var param_search = "query=";

var page_param = "page=";

exports.default_query = default_query;
exports.path_base = path_base;
exports.path_search = path_search;
exports.param_search = param_search;
exports.page_param = page_param;
/* No side effect */
