// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./App.bs.js");
var RegisterServiceWorker = require("./registerServiceWorker");

((require('./index.css')));

function register_service_worker(prim) {
  RegisterServiceWorker.default();
  return /* () */0;
}

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, { }), "root");

RegisterServiceWorker.default();

exports.register_service_worker = register_service_worker;
/*  Not a pure module */
