// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseDataJson(json) {
  return /* record */[
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json),
          /* author */Json_decode.field("author", Json_decode.string, json),
          /* num_comments */Json_decode.field("num_comments", Json_decode.$$int, json),
          /* points */Json_decode.field("points", Json_decode.$$int, json),
          /* objectID */Json_decode.field("objectID", Json_decode.string, json)
        ];
}

function parseDataResponseJson(json) {
  return Json_decode.field("hits", (function (param) {
                return Json_decode.list(parseDataJson, param);
              }), json);
}

exports.parseDataJson = parseDataJson;
exports.parseDataResponseJson = parseDataResponseJson;
/* No side effect */
