// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Utils$ReactHooksTemplate = require("./Utils.bs.js");

function Search(Props) {
  var value = Props.value;
  var onChange = Props.onChange;
  var onSubmit = Props.onSubmit;
  return React.createElement("form", {
              onSubmit: onSubmit
            }, React.createElement("input", {
                  type: "text",
                  value: value,
                  onChange: onChange
                }), React.createElement("button", {
                  type: "submit"
                }, Utils$ReactHooksTemplate.s2e("Search")));
}

var make = Search;

exports.make = make;
/* react Not a pure module */
