// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Utils$ReactHooksTemplate = require("./Utils.bs.js");
var Button$ReactHooksTemplate = require("./Button.bs.js");

function mk_sty(x) {
  return {
          width: x
        };
}

function Table(Props) {
  var list = Props.list;
  var onDissmiss = Props.onDissmiss;
  return React.createElement("div", {
              className: "table"
            }, React.createElement("div", {
                  className: "table-header"
                }, React.createElement("span", {
                      style: mk_sty("40%")
                    }, Utils$ReactHooksTemplate.s2e("Title")), React.createElement("span", {
                      style: mk_sty("30%")
                    }, Utils$ReactHooksTemplate.s2e("Author")), React.createElement("span", {
                      style: mk_sty("10%")
                    }, Utils$ReactHooksTemplate.s2e("Comments")), React.createElement("span", {
                      style: mk_sty("10%")
                    }, Utils$ReactHooksTemplate.s2e("Points")), React.createElement("span", {
                      style: mk_sty("10%")
                    }, Utils$ReactHooksTemplate.s2e("Archive"))), Utils$ReactHooksTemplate.l2e(List.map((function (item) {
                        return React.createElement("div", {
                                    key: item[/* objectID */5],
                                    className: "table-row"
                                  }, React.createElement("span", {
                                        style: mk_sty("40%")
                                      }, React.createElement("a", {
                                            href: item[/* url */1]
                                          }, Utils$ReactHooksTemplate.s2e(item[/* title */0]))), React.createElement("span", {
                                        style: mk_sty("30%")
                                      }, Utils$ReactHooksTemplate.s2e(item[/* author */2])), React.createElement("span", {
                                        style: mk_sty("10%")
                                      }, Utils$ReactHooksTemplate.i2e(item[/* num_comments */3])), React.createElement("span", {
                                        style: mk_sty("10%")
                                      }, Utils$ReactHooksTemplate.i2e(item[/* points */4])), React.createElement("span", {
                                        style: mk_sty("10%")
                                      }, React.createElement(Button$ReactHooksTemplate.make, {
                                            onClick: Curry._1(onDissmiss, item[/* objectID */5]),
                                            children: Utils$ReactHooksTemplate.s2e("Dissmiss")
                                          })));
                      }), list)));
}

var make = Table;

exports.mk_sty = mk_sty;
exports.make = make;
/* react Not a pure module */
