// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function s2e(prim) {
  return prim;
}

function i2e(x) {
  return String(x);
}

var l2e = $$Array.of_list;

exports.s2e = s2e;
exports.i2e = i2e;
exports.l2e = l2e;
/* No side effect */
