// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Utils$ReactHooksTemplate = require("./Utils.bs.js");
var Button$ReactHooksTemplate = require("./Button.bs.js");

function WithLoad(Props) {
  var onClick = Props.onClick;
  var isLoading = Props.isLoading;
  var children = Props.children;
  if (isLoading) {
    return React.createElement("div", undefined, Utils$ReactHooksTemplate.s2e("Loading..."));
  } else {
    return React.createElement(Button$ReactHooksTemplate.make, {
                onClick: onClick,
                children: children
              });
  }
}

var make = WithLoad;

exports.make = make;
/* react Not a pure module */
